import os
import sys
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline

from src.utils.logger import logging
from src.utils.exception import CustomException
from src.utils.common import create_directories, save_object

class DataTransformation:
    def __init__(self, config: dict):
        """
        Initializes configuration settings for saving the transformation pipeline objects.
        """
        self.config = config['data_transformation']

    def get_data_transformer_object(self) -> ColumnTransformer:
        """
        Constructs and returns a unified preprocessing pipeline for numerical 
        and categorical features.
        """
        try:
            logging.info("Building data transformation pipelines...")
            
            # Define specific column feature splits
            num_columns = ["carat", "depth", "table", "x", "y", "z"]
            cat_columns = ["cut", "color", "clarity"]

            # Numerical Pipeline: Handle missing records + scale values
            num_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", StandardScaler())
                ]
            )

            # Categorical Pipeline: Handle missing categories + encode text to numbers
            cat_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("one_hot_encoder", OneHotEncoder(handle_unknown="ignore")),
                    ("scaler", StandardScaler(with_mean=False))
                ]
            )

            logging.info(f"Numerical features handled: {num_columns}")
            logging.info(f"Categorical features handled: {cat_columns}")

            # Combine pipelines into a single ColumnTransformer layout
            preprocessor = ColumnTransformer(
                transformers=[
                    ("num_pipeline", num_pipeline, num_columns),
                    ("cat_pipeline", cat_pipeline, cat_columns)
                ]
            )

            return preprocessor

        except Exception as e:
            raise CustomException(e, sys)

    def initiate_data_transformation(self, train_path: str, test_path: str) -> tuple:
        """
        Reads train/test splits, applies transformations, and pickles the preprocessor configuration.
        """
        logging.info("===== Data Transformation Phase Started =====")
        try:
            # 1. Read the split datasets generated by the ingestion engine
            train_df = pd.read_csv(train_path)
            test_df = pd.read_csv(test_path)
            logging.info("Train and Test splits loaded successfully for preprocessing.")

            # 2. Extract our target feature ("price") from the dataframes
            target_column_name = "price"
            
            input_feature_train_df = train_df.drop(columns=[target_column_name], axis=1)
            target_feature_train_df = train_df[target_column_name]

            input_feature_test_df = test_df.drop(columns=[target_column_name], axis=1)
            target_feature_test_df = test_df[target_column_name]

            # 3. Obtain our core preprocessing transformer sequence
            preprocessing_obj = self.get_data_transformer_object()

            # 4. Fit and execute transformations across features
            logging.info("Applying preprocessing transformer adjustments to datasets...")
            input_feature_train_arr = preprocessing_obj.fit_transform(input_feature_train_df)
            input_feature_test_arr = preprocessing_obj.transform(input_feature_test_df)

            # 5. Concatenate input arrays back with target arrays for training compatibility
            # target values must be converted to numpy matrix blocks using np.c_
            train_arr = np.c_[input_feature_train_arr, np.array(target_feature_train_df)]
            test_arr = np.c_[input_feature_test_arr, np.array(target_feature_test_df)]

            # 6. Verify and establish artifact output destinations
            processed_dir = self.config['processed_dir']
            create_directories([processed_dir])

            preprocessor_file_path = os.path.join(processed_dir, self.config['preprocessor_name'])
            
            # 7. Serialize and save the fitted preprocessing pipeline asset
            save_object(
                file_path=preprocessor_file_path,
                obj=preprocessing_obj
            )

            logging.info("===== Data Transformation Phase Completed Successfully =====")
            
            # Returns transformed matrix arrays alongside the pickle file path layout
            return (
                train_arr,
                test_arr,
                preprocessor_file_path
            )

        except Exception as e:
            raise CustomException(e, sys)